### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by thiagoribeirodamotta** [ankurhanda/imageutilities#1]
Hi,

What are the modifications made to this lib ?
Would you mind telling me which packages are needed in order to succesfully build it?
It seems that some includes are specific to linux, like the include to helper_math.h in iucutil.h, or have I done something wrong with cmake ? It also seems that helper_math.h should be located at src folder, but it isnt there.
Which opencv version should be used?

Can you actually build it on Windows? Im currently using Windows 7 x64

Thank you.

**Comment by ankurhanda** [comment]
I had the helper_math.h path hardcoded "#include "/usr/local/cuda/samples/common/inc/helper_math.h""  in the iucutil.h. Can you find the equivalent path of helper_math.h in your system and replace that there?

**Comment by thiagoribeirodamotta** [comment]
Sure! Got that one done :)

The main problem right now is that it seems that all CUDA methods arent recognized by any .CPP, so I keep getting a bunch of unresolved external. Any idea why ?

**Comment by ankurhanda** [comment]
Can you post the errors here? Hard to tell what's going on otherwise.

**Comment by thiagoribeirodamotta** [comment]
Actually, I was able to solve them by recreating the iucore project as a  CUDA 7.5 Runtime project and adding those C/C++ Additional Include Directories to CUDA C/C++ Additional Include Directories. It wouldnt work otherwise.

**Comment by ankurhanda** [comment]
Great!
